version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Tehran
    labels: [dependencies, go]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /container
    schedule:
      interval: weekly
      day: monday
      time: "04:15"
      timezone: Asia/Tehran
    labels: [dependencies, container]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Tehran
    labels: [dependencies, ci]
    open-pull-requests-limit: 5
